name: 'Merge helm charts'
description: 'An action to merge two helm charts, copy and overwrite templates files, merge root items of yamls in root path'
inputs:
  source-path:
    description: 'Source path chart folder'
    required: true
  destination-path:
    description: 'Destination chart folder'
    required: true
  merge-yamls:
    description: 'Yaml file to be merged, separate by comma or newline'
    required: false
    default: "values.yaml"
  merge-directories:
    description: 'Directories to be replaced, separate by comma or newline'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-merge'
  color: 'blue'
