name: 'Merge helm charts'
description: 'An action to merge two helm charts, copy and overwrite templates files, merge root items of yamls in root path'
inputs:
  source-path:
    description: 'Source path chart folder'
    required: true
  destination-path:
    description: 'Destination chart folder'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-merge'
  color: 'blue'
